apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubesynth.fullname" . }}-provider-registry
  labels:
    {{- include "kubesynth.labels" . | nindent 4 }}
data:
  providers.json: |
    {"version":1,"custom_providers":{}}
