"""Kubernetes manifest builders package.

§2.1b of the road-to-prod plan: builder functions extracted from the
operator monolith.
"""

from builders.helpers import (
    KUBERNETES_RESOURCE_NAME_PATTERN,
    POD_TEMPLATE_REVISION_ANNOTATION,
    STORAGE_QUANTITY_MULTIPLIERS,
    agent_baseline_egress_rules,
    agent_baseline_ingress_peers,
    artifact_file_path,
    build_artifact_ref,
    build_journal_ref,
    build_pvc_spec,
    hashed_resource_name,
    platform_namespace_selector,
    resolved_api_gateway_internal_url,
    sandbox_name,
    slugify_name,
    worker_artifact_pvc_name,
    worker_passthrough_env,
    _parse_storage_quantity,
)

from builders.manifests import (
    PLATFORM_MANAGED_AGENT_ENV,
    PLATFORM_MANAGED_CODEX_ENV,
    PLATFORM_MANAGED_GOOSE_ENV,
    PLATFORM_MANAGED_OPENCODE_ENV,
    _auto_inject_mcp_sidecars,
    _build_pod_template_revision,
    _extract_skill_mcp_servers,
    _extract_statefulset_storage_request,
    _statefulset_template_signature,
    _validate_mcp_sidecars,
    _worker_git_env,
    agent_runtime_extra_env_items,
    codex_runtime_extra_env_items,
    create_a2a_egress_network_policy_manifest,
    create_a2a_ingress_network_policy_manifest,
    create_agent_service_manifest,
    create_agent_statefulset_manifest,
    create_mcp_auth_secret_manifest,
    create_mcp_network_policy_manifest,
    create_worker_artifact_pvc_manifest,
    create_worker_job_manifest,
    goose_runtime_extra_env_items,
    merged_codex_runtime_config_files,
    merged_goose_runtime_config_files,
    merged_opencode_runtime_config_files,
    opencode_runtime_extra_env_items,
    resolve_runtime_kind,
    runtime_extra_env_items,
    validate_runtime_configuration,
)

__all__ = [
    # helpers
    "KUBERNETES_RESOURCE_NAME_PATTERN",
    "POD_TEMPLATE_REVISION_ANNOTATION",
    "STORAGE_QUANTITY_MULTIPLIERS",
    "agent_baseline_egress_rules",
    "agent_baseline_ingress_peers",
    "artifact_file_path",
    "build_artifact_ref",
    "build_journal_ref",
    "build_pvc_spec",
    "hashed_resource_name",
    "platform_namespace_selector",
    "resolved_api_gateway_internal_url",
    "sandbox_name",
    "slugify_name",
    "worker_artifact_pvc_name",
    "worker_passthrough_env",
    "_parse_storage_quantity",
    # manifests
    "PLATFORM_MANAGED_AGENT_ENV",
    "PLATFORM_MANAGED_CODEX_ENV",
    "PLATFORM_MANAGED_GOOSE_ENV",
    "PLATFORM_MANAGED_OPENCODE_ENV",
    "_auto_inject_mcp_sidecars",
    "_build_pod_template_revision",
    "_extract_skill_mcp_servers",
    "_extract_statefulset_storage_request",
    "_statefulset_template_signature",
    "_validate_mcp_sidecars",
    "_worker_git_env",
    "agent_runtime_extra_env_items",
    "codex_runtime_extra_env_items",
    "create_a2a_egress_network_policy_manifest",
    "create_a2a_ingress_network_policy_manifest",
    "create_agent_service_manifest",
    "create_agent_statefulset_manifest",
    "create_mcp_auth_secret_manifest",
    "create_mcp_network_policy_manifest",
    "create_worker_artifact_pvc_manifest",
    "create_worker_job_manifest",
    "goose_runtime_extra_env_items",
    "merged_codex_runtime_config_files",
    "merged_goose_runtime_config_files",
    "merged_opencode_runtime_config_files",
    "opencode_runtime_extra_env_items",
    "resolve_runtime_kind",
    "runtime_extra_env_items",
    "validate_runtime_configuration",
]
