"""initial_schema

Revision ID: f86efc4d2d16
Revises: 
Create Date: 2026-05-24 16:00:11.138383
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86efc4d2d16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_history',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('namespace', sa.String(length=256), nullable=False),
    sa.Column('alert_id', sa.String(length=16), nullable=False),
    sa.Column('alert_name', sa.String(length=256), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('condition_matched', sa.String(length=512), nullable=False),
    sa.Column('action_taken', sa.String(length=32), nullable=False),
    sa.Column('agent_invoked', sa.String(length=256), nullable=True),
    sa.Column('invoke_status', sa.Integer(), nullable=True),
    sa.Column('invoke_error', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(length=16), nullable=True),
    sa.Column('snippet', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_alert_id'), 'alert_history', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_history_namespace'), 'alert_history', ['namespace'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_sub', sa.String(length=255), nullable=True),
    sa.Column('actor_username', sa.String(length=128), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=True),
    sa.Column('auth_provider', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_kind', sa.String(length=64), nullable=True),
    sa.Column('resource_name', sa.String(length=128), nullable=True),
    sa.Column('resource_namespace', sa.String(length=128), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_type'), 'audit_logs', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_kind'), 'audit_logs', ['resource_kind'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('tool_node', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'agent_name', 'session_id', name='uq_chat_sessions_identity')
    )
    op.create_index(op.f('ix_chat_sessions_agent_name'), 'chat_sessions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_chat_sessions_namespace'), 'chat_sessions', ['namespace'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=False)
    op.create_table('execution_traces',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('workflow_name', sa.String(length=256), nullable=False),
    sa.Column('namespace', sa.String(length=256), nullable=False),
    sa.Column('agent_name', sa.String(length=256), nullable=True),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_preview', sa.String(length=2000), nullable=True),
    sa.Column('output_preview', sa.String(length=2000), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('llm_call_count', sa.Integer(), nullable=False),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('steps_json', sa.JSON(), nullable=True),
    sa.Column('llm_calls_json', sa.JSON(), nullable=True),
    sa.Column('tool_calls_json', sa.JSON(), nullable=True),
    sa.Column('events_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_traces_agent_name'), 'execution_traces', ['agent_name'], unique=False)
    op.create_index(op.f('ix_execution_traces_namespace'), 'execution_traces', ['namespace'], unique=False)
    op.create_index(op.f('ix_execution_traces_run_id'), 'execution_traces', ['run_id'], unique=False)
    op.create_index(op.f('ix_execution_traces_status'), 'execution_traces', ['status'], unique=False)
    op.create_index(op.f('ix_execution_traces_workflow_name'), 'execution_traces', ['workflow_name'], unique=False)
    op.create_table('intelligence_alerts',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('namespace', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('schedule_id', sa.String(length=16), nullable=True),
    sa.Column('condition_type', sa.String(length=32), nullable=False),
    sa.Column('condition_value', sa.String(length=1024), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('agent_name', sa.String(length=256), nullable=True),
    sa.Column('prompt_template', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_triggered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_alerts_namespace'), 'intelligence_alerts', ['namespace'], unique=False)
    op.create_table('intelligence_collectors',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('namespace', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('encrypted_token', sa.String(length=4096), nullable=True),
    sa.Column('cluster', sa.String(length=256), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registered_by', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_intelligence_collectors_namespace'), 'intelligence_collectors', ['namespace'], unique=False)
    op.create_table('intelligence_schedules',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('namespace', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('cron', sa.String(length=128), nullable=False),
    sa.Column('collector_id', sa.String(length=128), nullable=False),
    sa.Column('builtin', sa.String(length=128), nullable=True),
    sa.Column('script', sa.String(), nullable=True),
    sa.Column('script_type', sa.String(length=16), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_schedules_namespace'), 'intelligence_schedules', ['namespace'], unique=False)
    op.create_table('intelligence_tasks',
    sa.Column('task_id', sa.String(length=16), nullable=False),
    sa.Column('namespace', sa.String(length=256), nullable=False),
    sa.Column('collector_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('submitted_by', sa.String(length=256), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_intelligence_tasks_namespace'), 'intelligence_tasks', ['namespace'], unique=False)
    op.create_table('mcp_connections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('server_id', sa.String(length=128), nullable=False),
    sa.Column('transport', sa.String(length=32), nullable=False),
    sa.Column('auth_type', sa.String(length=64), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('credential_metadata_json', sa.JSON(), nullable=False),
    sa.Column('secret_name', sa.String(length=253), nullable=True),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('validation_message', sa.String(length=1024), nullable=True),
    sa.Column('validation_detail_json', sa.JSON(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'slug', name='uq_mcp_connections_namespace_slug')
    )
    op.create_index(op.f('ix_mcp_connections_namespace'), 'mcp_connections', ['namespace'], unique=False)
    op.create_index(op.f('ix_mcp_connections_server_id'), 'mcp_connections', ['server_id'], unique=False)
    op.create_table('memory_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('promote_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_records_agent_name'), 'memory_records', ['agent_name'], unique=False)
    op.create_index(op.f('ix_memory_records_content_hash'), 'memory_records', ['content_hash'], unique=False)
    op.create_index(op.f('ix_memory_records_created_at'), 'memory_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_memory_records_memory_type'), 'memory_records', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memory_records_namespace'), 'memory_records', ['namespace'], unique=False)
    op.create_index(op.f('ix_memory_records_promoted'), 'memory_records', ['promoted'], unique=False)
    op.create_index(op.f('ix_memory_records_score'), 'memory_records', ['score'], unique=False)
    op.create_index(op.f('ix_memory_records_session_id'), 'memory_records', ['session_id'], unique=False)
    op.create_table('schema_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger_namespace', sa.String(length=128), nullable=False),
    sa.Column('trigger_name', sa.String(length=128), nullable=False),
    sa.Column('webhook_name', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('workflow_name', sa.String(length=128), nullable=False),
    sa.Column('workflow_namespace', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_executions_event_id'), 'trigger_executions', ['event_id'], unique=False)
    op.create_index(op.f('ix_trigger_executions_trigger_name'), 'trigger_executions', ['trigger_name'], unique=False)
    op.create_index(op.f('ix_trigger_executions_trigger_namespace'), 'trigger_executions', ['trigger_namespace'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_agent_name'), 'usage_records', ['agent_name'], unique=False)
    op.create_index(op.f('ix_usage_records_model'), 'usage_records', ['model'], unique=False)
    op.create_index(op.f('ix_usage_records_namespace'), 'usage_records', ['namespace'], unique=False)
    op.create_index(op.f('ix_usage_records_timestamp'), 'usage_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('allowed_namespaces', sa.JSON(), nullable=False),
    sa.Column('auth_provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider', 'external_id', name='uq_users_provider_external'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('webhook_invocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('webhook_name', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('source_ip', sa.String(length=128), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload_size', sa.Integer(), nullable=False),
    sa.Column('payload_snippet', sa.String(length=1024), nullable=True),
    sa.Column('headers_json', sa.JSON(), nullable=True),
    sa.Column('matched_triggers', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_invocations_event_id'), 'webhook_invocations', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_invocations_namespace'), 'webhook_invocations', ['namespace'], unique=False)
    op.create_index('ix_webhook_invocations_ns_name_created', 'webhook_invocations', ['namespace', 'webhook_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_webhook_invocations_webhook_name'), 'webhook_invocations', ['webhook_name'], unique=False)
    op.create_table('webhook_receivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('secret_ref', sa.String(length=253), nullable=False),
    sa.Column('ip_allowlist', sa.JSON(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('max_payload_bytes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'name', name='uq_webhook_receivers_namespace_name')
    )
    op.create_index(op.f('ix_webhook_receivers_name'), 'webhook_receivers', ['name'], unique=False)
    op.create_index(op.f('ix_webhook_receivers_namespace'), 'webhook_receivers', ['namespace'], unique=False)
    op.create_table('workflow_run_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_name', sa.String(length=256), nullable=False),
    sa.Column('namespace', sa.String(length=256), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('phase', sa.String(length=64), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('completed_steps', sa.Integer(), nullable=True),
    sa.Column('failed_steps', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.String(length=256), nullable=True),
    sa.Column('input_text', sa.String(), nullable=True),
    sa.Column('summary_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_run_history_run_id'), 'workflow_run_history', ['run_id'], unique=False)
    op.create_index(op.f('ix_workflow_run_history_workflow_name'), 'workflow_run_history', ['workflow_name'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('resource_name', sa.String(length=128), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=False),
    sa.Column('spec_json', sa.JSON(), nullable=True),
    sa.Column('status_json', sa.JSON(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('step_results_json', sa.JSON(), nullable=True),
    sa.Column('step_states_json', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('journal_path', sa.String(length=512), nullable=True),
    sa.Column('worker_job_name', sa.String(length=128), nullable=True),
    sa.Column('pending_approval_name', sa.String(length=128), nullable=True),
    sa.Column('log_archive_text', sa.String(), nullable=True),
    sa.Column('log_archive_source', sa.String(length=64), nullable=True),
    sa.Column('log_archive_truncated', sa.Boolean(), nullable=False),
    sa.Column('log_archive_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'resource_name', 'run_id', name='uq_workflow_runs_identity')
    )
    op.create_index(op.f('ix_workflow_runs_namespace'), 'workflow_runs', ['namespace'], unique=False)
    op.create_index(op.f('ix_workflow_runs_phase'), 'workflow_runs', ['phase'], unique=False)
    op.create_index(op.f('ix_workflow_runs_resource_name'), 'workflow_runs', ['resource_name'], unique=False)
    op.create_index(op.f('ix_workflow_runs_run_id'), 'workflow_runs', ['run_id'], unique=False)
    op.create_table('workflow_triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_kind', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('event_filter_json', sa.JSON(), nullable=True),
    sa.Column('target_workflow_name', sa.String(length=128), nullable=False),
    sa.Column('target_workflow_namespace', sa.String(length=128), nullable=False),
    sa.Column('payload_mapping_json', sa.JSON(), nullable=False),
    sa.Column('retry_max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_backoff_seconds', sa.Integer(), nullable=False),
    sa.Column('notifications_on_success', sa.JSON(), nullable=False),
    sa.Column('notifications_on_failure', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'name', name='uq_workflow_triggers_namespace_name')
    )
    op.create_index(op.f('ix_workflow_triggers_name'), 'workflow_triggers', ['name'], unique=False)
    op.create_index(op.f('ix_workflow_triggers_namespace'), 'workflow_triggers', ['namespace'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('auth_provider', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_workflow_triggers_namespace'), table_name='workflow_triggers')
    op.drop_index(op.f('ix_workflow_triggers_name'), table_name='workflow_triggers')
    op.drop_table('workflow_triggers')
    op.drop_index(op.f('ix_workflow_runs_run_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_resource_name'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_phase'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_namespace'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_workflow_run_history_workflow_name'), table_name='workflow_run_history')
    op.drop_index(op.f('ix_workflow_run_history_run_id'), table_name='workflow_run_history')
    op.drop_table('workflow_run_history')
    op.drop_index(op.f('ix_webhook_receivers_namespace'), table_name='webhook_receivers')
    op.drop_index(op.f('ix_webhook_receivers_name'), table_name='webhook_receivers')
    op.drop_table('webhook_receivers')
    op.drop_index(op.f('ix_webhook_invocations_webhook_name'), table_name='webhook_invocations')
    op.drop_index('ix_webhook_invocations_ns_name_created', table_name='webhook_invocations')
    op.drop_index(op.f('ix_webhook_invocations_namespace'), table_name='webhook_invocations')
    op.drop_index(op.f('ix_webhook_invocations_event_id'), table_name='webhook_invocations')
    op.drop_table('webhook_invocations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_timestamp'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_namespace'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_model'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_agent_name'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_trigger_executions_trigger_namespace'), table_name='trigger_executions')
    op.drop_index(op.f('ix_trigger_executions_trigger_name'), table_name='trigger_executions')
    op.drop_index(op.f('ix_trigger_executions_event_id'), table_name='trigger_executions')
    op.drop_table('trigger_executions')
    op.drop_table('schema_version')
    op.drop_index(op.f('ix_memory_records_session_id'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_score'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_promoted'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_namespace'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_memory_type'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_created_at'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_content_hash'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_agent_name'), table_name='memory_records')
    op.drop_table('memory_records')
    op.drop_index(op.f('ix_mcp_connections_server_id'), table_name='mcp_connections')
    op.drop_index(op.f('ix_mcp_connections_namespace'), table_name='mcp_connections')
    op.drop_table('mcp_connections')
    op.drop_index(op.f('ix_intelligence_tasks_namespace'), table_name='intelligence_tasks')
    op.drop_table('intelligence_tasks')
    op.drop_index(op.f('ix_intelligence_schedules_namespace'), table_name='intelligence_schedules')
    op.drop_table('intelligence_schedules')
    op.drop_index(op.f('ix_intelligence_collectors_namespace'), table_name='intelligence_collectors')
    op.drop_table('intelligence_collectors')
    op.drop_index(op.f('ix_intelligence_alerts_namespace'), table_name='intelligence_alerts')
    op.drop_table('intelligence_alerts')
    op.drop_index(op.f('ix_execution_traces_workflow_name'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_status'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_run_id'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_namespace'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_agent_name'), table_name='execution_traces')
    op.drop_table('execution_traces')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_namespace'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_agent_name'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_audit_logs_resource_kind'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alert_history_namespace'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_alert_id'), table_name='alert_history')
    op.drop_table('alert_history')
    # ### end Alembic commands ###
