{{- if .Values.trustBundle.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default (printf "%s-trust-bundle" (include "kubesynapse.fullname" .)) .Values.trustBundle.configMapName }}
  labels:
    {{- include "kubesynapse.labels" . | nindent 4 }}
data:
  ca-bundle.pem: |
{{ .Files.Get "files/ca-bundle.pem" | indent 4 }}
{{- end }}
